package iso3166

// Code generated by country-states 0.0.1 (https://github.com/hajnalandor/country-states). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

type Country struct {
	Alpha2           string
	Alpha3           string
	Name             string
	OfficialName     string
	CommonName       string
	Numeric          string
	SubDivCodeToName map[string]SubDivisionNameWrapper
	SubDivNameToCode map[string]SubDivisionCodeWrapper
}

type SubDivisionNameWrapper struct {
	Name             string
	Type             string
	LocalName        string
	LanguageCode     string
	SubDivCodeToName map[string]SubDivisionNameWrapper
}

type SubDivisionCodeWrapper struct {
	Code             string
	SubDivNameToCode map[string]SubDivisionCodeWrapper
}

var CountryStates = map[string]Country{

	"AD": {
		Alpha2:       "AD",
		Alpha3:       "AND",
		Name:         "Andorra",
		OfficialName: "Principality of Andorra",
		CommonName:   "",
		Numeric:      "020",
	},

	"AE": {
		Alpha2:       "AE",
		Alpha3:       "ARE",
		Name:         "United Arab Emirates",
		OfficialName: "",
		CommonName:   "",
		Numeric:      "784",
	},

	"AF": {
		Alpha2:       "AF",
		Alpha3:       "AFG",
		Name:         "Afghanistan",
		OfficialName: "Islamic Republic of Afghanistan",
		CommonName:   "",
		Numeric:      "004",
	},

	"AG": {
		Alpha2:       "AG",
		Alpha3:       "ATG",
		Name:         "Antigua and Barbuda",
		OfficialName: "",
		CommonName:   "",
		Numeric:      "028",
	},

	"AI": {
		Alpha2:       "AI",
		Alpha3:       "AIA",
		Name:         "Anguilla",
		OfficialName: "",
		CommonName:   "",
		Numeric:      "660",
	},

	"AL": {
		Alpha2:       "AL",
		Alpha3:       "ALB",
		Name:         "Albania",
		OfficialName: "Republic of Albania",
		CommonName:   "",
		Numeric:      "008",
	},

	"AM": {
		Alpha2:       "AM",
		Alpha3:       "ARM",
		Name:         "Armenia",
		OfficialName: "Republic of Armenia",
		CommonName:   "",
		Numeric:      "051",
	},

	"AO": {
		Alpha2:       "AO",
		Alpha3:       "AGO",
		Name:         "Angola",
		OfficialName: "Republic of Angola",
		CommonName:   "",
		Numeric:      "024",
	},

	"AQ": {
		Alpha2:       "AQ",
		Alpha3:       "ATA",
		Name:         "Antarctica",
		OfficialName: "",
		CommonName:   "",
		Numeric:      "010",
	},

	"AR": {
		Alpha2:       "AR",
		Alpha3:       "ARG",
		Name:         "Argentina",
		OfficialName: "Argentine Republic",
		CommonName:   "",
		Numeric:      "032",
	},

	"AS": {
		Alpha2:       "AS",
		Alpha3:       "ASM",
		Name:         "American Samoa",
		OfficialName: "",
		CommonName:   "",
		Numeric:      "016",
	},

	"AT": {
		Alpha2:       "AT",
		Alpha3:       "AUT",
		Name:         "Austria",
		OfficialName: "Republic of Austria",
		CommonName:   "",
		Numeric:      "040",
	},

	"AU": {
		Alpha2:       "AU",
		Alpha3:       "AUS",
		Name:         "Australia",
		OfficialName: "",
		CommonName:   "",
		Numeric:      "036",
	},

	"AW": {
		Alpha2:       "AW",
		Alpha3:       "ABW",
		Name:         "Aruba",
		OfficialName: "",
		CommonName:   "",
		Numeric:      "533",
	},

	"AX": {
		Alpha2:       "AX",
		Alpha3:       "ALA",
		Name:         "Åland Islands",
		OfficialName: "",
		CommonName:   "",
		Numeric:      "248",
	},

	"AZ": {
		Alpha2:       "AZ",
		Alpha3:       "AZE",
		Name:         "Azerbaijan",
		OfficialName: "Republic of Azerbaijan",
		CommonName:   "",
		Numeric:      "031",
	},

	"BA": {
		Alpha2:       "BA",
		Alpha3:       "BIH",
		Name:         "Bosnia and Herzegovina",
		OfficialName: "Republic of Bosnia and Herzegovina",
		CommonName:   "",
		Numeric:      "070",
	},

	"BB": {
		Alpha2:       "BB",
		Alpha3:       "BRB",
		Name:         "Barbados",
		OfficialName: "",
		CommonName:   "",
		Numeric:      "052",
	},

	"BD": {
		Alpha2:       "BD",
		Alpha3:       "BGD",
		Name:         "Bangladesh",
		OfficialName: "People's Republic of Bangladesh",
		CommonName:   "",
		Numeric:      "050",
	},

	"BE": {
		Alpha2:       "BE",
		Alpha3:       "BEL",
		Name:         "Belgium",
		OfficialName: "Kingdom of Belgium",
		CommonName:   "",
		Numeric:      "056",
	},

	"BF": {
		Alpha2:       "BF",
		Alpha3:       "BFA",
		Name:         "Burkina Faso",
		OfficialName: "",
		CommonName:   "",
		Numeric:      "854",
	},

	"BG": {
		Alpha2:       "BG",
		Alpha3:       "BGR",
		Name:         "Bulgaria",
		OfficialName: "Republic of Bulgaria",
		CommonName:   "",
		Numeric:      "100",
	},

	"BH": {
		Alpha2:       "BH",
		Alpha3:       "BHR",
		Name:         "Bahrain",
		OfficialName: "Kingdom of Bahrain",
		CommonName:   "",
		Numeric:      "048",
	},

	"BI": {
		Alpha2:       "BI",
		Alpha3:       "BDI",
		Name:         "Burundi",
		OfficialName: "Republic of Burundi",
		CommonName:   "",
		Numeric:      "108",
	},

	"BJ": {
		Alpha2:       "BJ",
		Alpha3:       "BEN",
		Name:         "Benin",
		OfficialName: "Republic of Benin",
		CommonName:   "",
		Numeric:      "204",
	},

	"BL": {
		Alpha2:       "BL",
		Alpha3:       "BLM",
		Name:         "Saint Barthélemy",
		OfficialName: "",
		CommonName:   "",
		Numeric:      "652",
	},

	"BM": {
		Alpha2:       "BM",
		Alpha3:       "BMU",
		Name:         "Bermuda",
		OfficialName: "",
		CommonName:   "",
		Numeric:      "060",
	},

	"BN": {
		Alpha2:       "BN",
		Alpha3:       "BRN",
		Name:         "Brunei Darussalam",
		OfficialName: "",
		CommonName:   "",
		Numeric:      "096",
	},

	"BO": {
		Alpha2:       "BO",
		Alpha3:       "BOL",
		Name:         "Bolivia, Plurinational State of",
		OfficialName: "Plurinational State of Bolivia",
		CommonName:   "Bolivia",
		Numeric:      "068",
	},

	"BQ": {
		Alpha2:       "BQ",
		Alpha3:       "BES",
		Name:         "Bonaire, Sint Eustatius and Saba",
		OfficialName: "Bonaire, Sint Eustatius and Saba",
		CommonName:   "",
		Numeric:      "535",
	},

	"BR": {
		Alpha2:       "BR",
		Alpha3:       "BRA",
		Name:         "Brazil",
		OfficialName: "Federative Republic of Brazil",
		CommonName:   "",
		Numeric:      "076",
	},

	"BS": {
		Alpha2:       "BS",
		Alpha3:       "BHS",
		Name:         "Bahamas",
		OfficialName: "Commonwealth of the Bahamas",
		CommonName:   "",
		Numeric:      "044",
	},

	"BT": {
		Alpha2:       "BT",
		Alpha3:       "BTN",
		Name:         "Bhutan",
		OfficialName: "Kingdom of Bhutan",
		CommonName:   "",
		Numeric:      "064",
	},

	"BV": {
		Alpha2:       "BV",
		Alpha3:       "BVT",
		Name:         "Bouvet Island",
		OfficialName: "",
		CommonName:   "",
		Numeric:      "074",
	},

	"BW": {
		Alpha2:       "BW",
		Alpha3:       "BWA",
		Name:         "Botswana",
		OfficialName: "Republic of Botswana",
		CommonName:   "",
		Numeric:      "072",
	},

	"BY": {
		Alpha2:       "BY",
		Alpha3:       "BLR",
		Name:         "Belarus",
		OfficialName: "Republic of Belarus",
		CommonName:   "",
		Numeric:      "112",
	},

	"BZ": {
		Alpha2:       "BZ",
		Alpha3:       "BLZ",
		Name:         "Belize",
		OfficialName: "",
		CommonName:   "",
		Numeric:      "084",
	},

	"CA": {
		Alpha2:       "CA",
		Alpha3:       "CAN",
		Name:         "Canada",
		OfficialName: "",
		CommonName:   "",
		Numeric:      "124",
	},

	"CC": {
		Alpha2:       "CC",
		Alpha3:       "CCK",
		Name:         "Cocos (Keeling) Islands",
		OfficialName: "",
		CommonName:   "",
		Numeric:      "166",
	},

	"CD": {
		Alpha2:       "CD",
		Alpha3:       "COD",
		Name:         "Congo, The Democratic Republic of the",
		OfficialName: "",
		CommonName:   "",
		Numeric:      "180",
	},

	"CF": {
		Alpha2:       "CF",
		Alpha3:       "CAF",
		Name:         "Central African Republic",
		OfficialName: "",
		CommonName:   "",
		Numeric:      "140",
	},

	"CG": {
		Alpha2:       "CG",
		Alpha3:       "COG",
		Name:         "Congo",
		OfficialName: "Republic of the Congo",
		CommonName:   "",
		Numeric:      "178",
	},

	"CH": {
		Alpha2:       "CH",
		Alpha3:       "CHE",
		Name:         "Switzerland",
		OfficialName: "Swiss Confederation",
		CommonName:   "",
		Numeric:      "756",
	},

	"CI": {
		Alpha2:       "CI",
		Alpha3:       "CIV",
		Name:         "Côte d'Ivoire",
		OfficialName: "Republic of Côte d'Ivoire",
		CommonName:   "",
		Numeric:      "384",
	},

	"CK": {
		Alpha2:       "CK",
		Alpha3:       "COK",
		Name:         "Cook Islands",
		OfficialName: "",
		CommonName:   "",
		Numeric:      "184",
	},

	"CL": {
		Alpha2:       "CL",
		Alpha3:       "CHL",
		Name:         "Chile",
		OfficialName: "Republic of Chile",
		CommonName:   "",
		Numeric:      "152",
	},

	"CM": {
		Alpha2:       "CM",
		Alpha3:       "CMR",
		Name:         "Cameroon",
		OfficialName: "Republic of Cameroon",
		CommonName:   "",
		Numeric:      "120",
	},

	"CN": {
		Alpha2:       "CN",
		Alpha3:       "CHN",
		Name:         "China",
		OfficialName: "People's Republic of China",
		CommonName:   "",
		Numeric:      "156",
	},

	"CO": {
		Alpha2:       "CO",
		Alpha3:       "COL",
		Name:         "Colombia",
		OfficialName: "Republic of Colombia",
		CommonName:   "",
		Numeric:      "170",
	},

	"CR": {
		Alpha2:       "CR",
		Alpha3:       "CRI",
		Name:         "Costa Rica",
		OfficialName: "Republic of Costa Rica",
		CommonName:   "",
		Numeric:      "188",
	},

	"CU": {
		Alpha2:       "CU",
		Alpha3:       "CUB",
		Name:         "Cuba",
		OfficialName: "Republic of Cuba",
		CommonName:   "",
		Numeric:      "192",
	},

	"CV": {
		Alpha2:       "CV",
		Alpha3:       "CPV",
		Name:         "Cabo Verde",
		OfficialName: "Republic of Cabo Verde",
		CommonName:   "",
		Numeric:      "132",
	},

	"CW": {
		Alpha2:       "CW",
		Alpha3:       "CUW",
		Name:         "Curaçao",
		OfficialName: "Curaçao",
		CommonName:   "",
		Numeric:      "531",
	},

	"CX": {
		Alpha2:       "CX",
		Alpha3:       "CXR",
		Name:         "Christmas Island",
		OfficialName: "",
		CommonName:   "",
		Numeric:      "162",
	},

	"CY": {
		Alpha2:       "CY",
		Alpha3:       "CYP",
		Name:         "Cyprus",
		OfficialName: "Republic of Cyprus",
		CommonName:   "",
		Numeric:      "196",
	},

	"CZ": {
		Alpha2:       "CZ",
		Alpha3:       "CZE",
		Name:         "Czechia",
		OfficialName: "Czech Republic",
		CommonName:   "",
		Numeric:      "203",
	},

	"DE": {
		Alpha2:       "DE",
		Alpha3:       "DEU",
		Name:         "Germany",
		OfficialName: "Federal Republic of Germany",
		CommonName:   "",
		Numeric:      "276",
	},

	"DJ": {
		Alpha2:       "DJ",
		Alpha3:       "DJI",
		Name:         "Djibouti",
		OfficialName: "Republic of Djibouti",
		CommonName:   "",
		Numeric:      "262",
	},

	"DK": {
		Alpha2:       "DK",
		Alpha3:       "DNK",
		Name:         "Denmark",
		OfficialName: "Kingdom of Denmark",
		CommonName:   "",
		Numeric:      "208",
	},

	"DM": {
		Alpha2:       "DM",
		Alpha3:       "DMA",
		Name:         "Dominica",
		OfficialName: "Commonwealth of Dominica",
		CommonName:   "",
		Numeric:      "212",
	},

	"DO": {
		Alpha2:       "DO",
		Alpha3:       "DOM",
		Name:         "Dominican Republic",
		OfficialName: "",
		CommonName:   "",
		Numeric:      "214",
	},

	"DZ": {
		Alpha2:       "DZ",
		Alpha3:       "DZA",
		Name:         "Algeria",
		OfficialName: "People's Democratic Republic of Algeria",
		CommonName:   "",
		Numeric:      "012",
	},

	"EC": {
		Alpha2:       "EC",
		Alpha3:       "ECU",
		Name:         "Ecuador",
		OfficialName: "Republic of Ecuador",
		CommonName:   "",
		Numeric:      "218",
	},

	"EE": {
		Alpha2:       "EE",
		Alpha3:       "EST",
		Name:         "Estonia",
		OfficialName: "Republic of Estonia",
		CommonName:   "",
		Numeric:      "233",
	},

	"EG": {
		Alpha2:       "EG",
		Alpha3:       "EGY",
		Name:         "Egypt",
		OfficialName: "Arab Republic of Egypt",
		CommonName:   "",
		Numeric:      "818",
	},

	"EH": {
		Alpha2:       "EH",
		Alpha3:       "ESH",
		Name:         "Western Sahara",
		OfficialName: "",
		CommonName:   "",
		Numeric:      "732",
	},

	"ER": {
		Alpha2:       "ER",
		Alpha3:       "ERI",
		Name:         "Eritrea",
		OfficialName: "the State of Eritrea",
		CommonName:   "",
		Numeric:      "232",
	},

	"ES": {
		Alpha2:       "ES",
		Alpha3:       "ESP",
		Name:         "Spain",
		OfficialName: "Kingdom of Spain",
		CommonName:   "",
		Numeric:      "724",
	},

	"ET": {
		Alpha2:       "ET",
		Alpha3:       "ETH",
		Name:         "Ethiopia",
		OfficialName: "Federal Democratic Republic of Ethiopia",
		CommonName:   "",
		Numeric:      "231",
	},

	"FI": {
		Alpha2:       "FI",
		Alpha3:       "FIN",
		Name:         "Finland",
		OfficialName: "Republic of Finland",
		CommonName:   "",
		Numeric:      "246",
	},

	"FJ": {
		Alpha2:       "FJ",
		Alpha3:       "FJI",
		Name:         "Fiji",
		OfficialName: "Republic of Fiji",
		CommonName:   "",
		Numeric:      "242",
	},

	"FK": {
		Alpha2:       "FK",
		Alpha3:       "FLK",
		Name:         "Falkland Islands (Malvinas)",
		OfficialName: "",
		CommonName:   "",
		Numeric:      "238",
	},

	"FM": {
		Alpha2:       "FM",
		Alpha3:       "FSM",
		Name:         "Micronesia, Federated States of",
		OfficialName: "Federated States of Micronesia",
		CommonName:   "",
		Numeric:      "583",
	},

	"FO": {
		Alpha2:       "FO",
		Alpha3:       "FRO",
		Name:         "Faroe Islands",
		OfficialName: "",
		CommonName:   "",
		Numeric:      "234",
	},

	"FR": {
		Alpha2:       "FR",
		Alpha3:       "FRA",
		Name:         "France",
		OfficialName: "French Republic",
		CommonName:   "",
		Numeric:      "250",
	},

	"GA": {
		Alpha2:       "GA",
		Alpha3:       "GAB",
		Name:         "Gabon",
		OfficialName: "Gabonese Republic",
		CommonName:   "",
		Numeric:      "266",
	},

	"GB": {
		Alpha2:       "GB",
		Alpha3:       "GBR",
		Name:         "United Kingdom",
		OfficialName: "United Kingdom of Great Britain and Northern Ireland",
		CommonName:   "",
		Numeric:      "826",
	},

	"GD": {
		Alpha2:       "GD",
		Alpha3:       "GRD",
		Name:         "Grenada",
		OfficialName: "",
		CommonName:   "",
		Numeric:      "308",
	},

	"GE": {
		Alpha2:       "GE",
		Alpha3:       "GEO",
		Name:         "Georgia",
		OfficialName: "",
		CommonName:   "",
		Numeric:      "268",
	},

	"GF": {
		Alpha2:       "GF",
		Alpha3:       "GUF",
		Name:         "French Guiana",
		OfficialName: "",
		CommonName:   "",
		Numeric:      "254",
	},

	"GG": {
		Alpha2:       "GG",
		Alpha3:       "GGY",
		Name:         "Guernsey",
		OfficialName: "",
		CommonName:   "",
		Numeric:      "831",
	},

	"GH": {
		Alpha2:       "GH",
		Alpha3:       "GHA",
		Name:         "Ghana",
		OfficialName: "Republic of Ghana",
		CommonName:   "",
		Numeric:      "288",
	},

	"GI": {
		Alpha2:       "GI",
		Alpha3:       "GIB",
		Name:         "Gibraltar",
		OfficialName: "",
		CommonName:   "",
		Numeric:      "292",
	},

	"GL": {
		Alpha2:       "GL",
		Alpha3:       "GRL",
		Name:         "Greenland",
		OfficialName: "",
		CommonName:   "",
		Numeric:      "304",
	},

	"GM": {
		Alpha2:       "GM",
		Alpha3:       "GMB",
		Name:         "Gambia",
		OfficialName: "Republic of the Gambia",
		CommonName:   "",
		Numeric:      "270",
	},

	"GN": {
		Alpha2:       "GN",
		Alpha3:       "GIN",
		Name:         "Guinea",
		OfficialName: "Republic of Guinea",
		CommonName:   "",
		Numeric:      "324",
	},

	"GP": {
		Alpha2:       "GP",
		Alpha3:       "GLP",
		Name:         "Guadeloupe",
		OfficialName: "",
		CommonName:   "",
		Numeric:      "312",
	},

	"GQ": {
		Alpha2:       "GQ",
		Alpha3:       "GNQ",
		Name:         "Equatorial Guinea",
		OfficialName: "Republic of Equatorial Guinea",
		CommonName:   "",
		Numeric:      "226",
	},

	"GR": {
		Alpha2:       "GR",
		Alpha3:       "GRC",
		Name:         "Greece",
		OfficialName: "Hellenic Republic",
		CommonName:   "",
		Numeric:      "300",
	},

	"GS": {
		Alpha2:       "GS",
		Alpha3:       "SGS",
		Name:         "South Georgia and the South Sandwich Islands",
		OfficialName: "",
		CommonName:   "",
		Numeric:      "239",
	},

	"GT": {
		Alpha2:       "GT",
		Alpha3:       "GTM",
		Name:         "Guatemala",
		OfficialName: "Republic of Guatemala",
		CommonName:   "",
		Numeric:      "320",
	},

	"GU": {
		Alpha2:       "GU",
		Alpha3:       "GUM",
		Name:         "Guam",
		OfficialName: "",
		CommonName:   "",
		Numeric:      "316",
	},

	"GW": {
		Alpha2:       "GW",
		Alpha3:       "GNB",
		Name:         "Guinea-Bissau",
		OfficialName: "Republic of Guinea-Bissau",
		CommonName:   "",
		Numeric:      "624",
	},

	"GY": {
		Alpha2:       "GY",
		Alpha3:       "GUY",
		Name:         "Guyana",
		OfficialName: "Republic of Guyana",
		CommonName:   "",
		Numeric:      "328",
	},

	"HK": {
		Alpha2:       "HK",
		Alpha3:       "HKG",
		Name:         "Hong Kong",
		OfficialName: "Hong Kong Special Administrative Region of China",
		CommonName:   "",
		Numeric:      "344",
	},

	"HM": {
		Alpha2:       "HM",
		Alpha3:       "HMD",
		Name:         "Heard Island and McDonald Islands",
		OfficialName: "",
		CommonName:   "",
		Numeric:      "334",
	},

	"HN": {
		Alpha2:       "HN",
		Alpha3:       "HND",
		Name:         "Honduras",
		OfficialName: "Republic of Honduras",
		CommonName:   "",
		Numeric:      "340",
	},

	"HR": {
		Alpha2:       "HR",
		Alpha3:       "HRV",
		Name:         "Croatia",
		OfficialName: "Republic of Croatia",
		CommonName:   "",
		Numeric:      "191",
	},

	"HT": {
		Alpha2:       "HT",
		Alpha3:       "HTI",
		Name:         "Haiti",
		OfficialName: "Republic of Haiti",
		CommonName:   "",
		Numeric:      "332",
	},

	"HU": {
		Alpha2:       "HU",
		Alpha3:       "HUN",
		Name:         "Hungary",
		OfficialName: "Hungary",
		CommonName:   "",
		Numeric:      "348",

		SubDivCodeToName: map[string]SubDivisionNameWrapper{

			"BA": {
				Name:         "Baranya",
				LocalName:    "",
				LanguageCode: "hu",
				Type:         "county",
			},
			"BC": {
				Name:         "Békéscsaba",
				LocalName:    "",
				LanguageCode: "hu",
				Type:         "city with county rights",
			},
			"BE": {
				Name:         "Békés",
				LocalName:    "",
				LanguageCode: "hu",
				Type:         "county",
			},
			"BK": {
				Name:         "Bács-Kiskun",
				LocalName:    "",
				LanguageCode: "hu",
				Type:         "county",
			},
			"BU": {
				Name:         "Budapest",
				LocalName:    "",
				LanguageCode: "hu",
				Type:         "capital city",
			},
			"BZ": {
				Name:         "Borsod-Abaúj-Zemplén",
				LocalName:    "",
				LanguageCode: "hu",
				Type:         "county",
			},
			"CS": {
				Name:         "Csongrád",
				LocalName:    "",
				LanguageCode: "hu",
				Type:         "county",
			},
			"DE": {
				Name:         "Debrecen",
				LocalName:    "",
				LanguageCode: "hu",
				Type:         "city with county rights",
			},
			"DU": {
				Name:         "Dunaújváros",
				LocalName:    "",
				LanguageCode: "hu",
				Type:         "city with county rights",
			},
			"EG": {
				Name:         "Eger",
				LocalName:    "",
				LanguageCode: "hu",
				Type:         "city with county rights",
			},
			"ER": {
				Name:         "Érd",
				LocalName:    "",
				LanguageCode: "hu",
				Type:         "city with county rights",
			},
			"FE": {
				Name:         "Fejér",
				LocalName:    "",
				LanguageCode: "hu",
				Type:         "county",
			},
			"GS": {
				Name:         "Győr-Moson-Sopron",
				LocalName:    "",
				LanguageCode: "hu",
				Type:         "county",
			},
			"GY": {
				Name:         "Győr",
				LocalName:    "",
				LanguageCode: "hu",
				Type:         "city with county rights",
			},
			"HB": {
				Name:         "Hajdú-Bihar",
				LocalName:    "",
				LanguageCode: "hu",
				Type:         "county",
			},
			"HE": {
				Name:         "Heves",
				LocalName:    "",
				LanguageCode: "hu",
				Type:         "county",
			},
			"HV": {
				Name:         "Hódmezővásárhely",
				LocalName:    "",
				LanguageCode: "hu",
				Type:         "city with county rights",
			},
			"JN": {
				Name:         "Jász-Nagykun-Szolnok",
				LocalName:    "",
				LanguageCode: "hu",
				Type:         "county",
			},
			"KE": {
				Name:         "Komárom-Esztergom",
				LocalName:    "",
				LanguageCode: "hu",
				Type:         "county",
			},
			"KM": {
				Name:         "Kecskemét",
				LocalName:    "",
				LanguageCode: "hu",
				Type:         "city with county rights",
			},
			"KV": {
				Name:         "Kaposvár",
				LocalName:    "",
				LanguageCode: "hu",
				Type:         "city with county rights",
			},
			"MI": {
				Name:         "Miskolc",
				LocalName:    "",
				LanguageCode: "hu",
				Type:         "city with county rights",
			},
			"NK": {
				Name:         "Nagykanizsa",
				LocalName:    "",
				LanguageCode: "hu",
				Type:         "city with county rights",
			},
			"NO": {
				Name:         "Nógrád",
				LocalName:    "",
				LanguageCode: "hu",
				Type:         "county",
			},
			"NY": {
				Name:         "Nyíregyháza",
				LocalName:    "",
				LanguageCode: "hu",
				Type:         "city with county rights",
			},
			"PE": {
				Name:         "Pest",
				LocalName:    "",
				LanguageCode: "hu",
				Type:         "county",
			},
			"PS": {
				Name:         "Pécs",
				LocalName:    "",
				LanguageCode: "hu",
				Type:         "city with county rights",
			},
			"SD": {
				Name:         "Szeged",
				LocalName:    "",
				LanguageCode: "hu",
				Type:         "city with county rights",
			},
			"SF": {
				Name:         "Székesfehérvár",
				LocalName:    "",
				LanguageCode: "hu",
				Type:         "city with county rights",
			},
			"SH": {
				Name:         "Szombathely",
				LocalName:    "",
				LanguageCode: "hu",
				Type:         "city with county rights",
			},
			"SK": {
				Name:         "Szolnok",
				LocalName:    "",
				LanguageCode: "hu",
				Type:         "city with county rights",
			},
			"SN": {
				Name:         "Sopron",
				LocalName:    "",
				LanguageCode: "hu",
				Type:         "city with county rights",
			},
			"SO": {
				Name:         "Somogy",
				LocalName:    "",
				LanguageCode: "hu",
				Type:         "county",
			},
			"SS": {
				Name:         "Szekszárd",
				LocalName:    "",
				LanguageCode: "hu",
				Type:         "city with county rights",
			},
			"ST": {
				Name:         "Salgótarján",
				LocalName:    "",
				LanguageCode: "hu",
				Type:         "city with county rights",
			},
			"SZ": {
				Name:         "Szabolcs-Szatmár-Bereg",
				LocalName:    "",
				LanguageCode: "hu",
				Type:         "county",
			},
			"TB": {
				Name:         "Tatabánya",
				LocalName:    "",
				LanguageCode: "hu",
				Type:         "city with county rights",
			},
			"TO": {
				Name:         "Tolna",
				LocalName:    "",
				LanguageCode: "hu",
				Type:         "county",
			},
			"VA": {
				Name:         "Vas",
				LocalName:    "",
				LanguageCode: "hu",
				Type:         "county",
			},
			"VE": {
				Name:         "Veszprém",
				LocalName:    "",
				LanguageCode: "hu",
				Type:         "county",
			},
			"VM": {
				Name:         "Veszprém",
				LocalName:    "",
				LanguageCode: "hu",
				Type:         "city with county rights",
			},
			"ZA": {
				Name:         "Zala",
				LocalName:    "",
				LanguageCode: "hu",
				Type:         "county",
			},
			"ZE": {
				Name:         "Zalaegerszeg",
				LocalName:    "",
				LanguageCode: "hu",
				Type:         "city with county rights",
			},
		},

		SubDivNameToCode: map[string]SubDivisionCodeWrapper{

			"Baranya": {
				Code: "BA",
			},
			"Borsod-Abaúj-Zemplén": {
				Code: "BZ",
			},
			"Budapest": {
				Code: "BU",
			},
			"Bács-Kiskun": {
				Code: "BK",
			},
			"Békés": {
				Code: "BE",
			},
			"Békéscsaba": {
				Code: "BC",
			},
			"Csongrád": {
				Code: "CS",
			},
			"Debrecen": {
				Code: "DE",
			},
			"Dunaújváros": {
				Code: "DU",
			},
			"Eger": {
				Code: "EG",
			},
			"Fejér": {
				Code: "FE",
			},
			"Győr": {
				Code: "GY",
			},
			"Győr-Moson-Sopron": {
				Code: "GS",
			},
			"Hajdú-Bihar": {
				Code: "HB",
			},
			"Heves": {
				Code: "HE",
			},
			"Hódmezővásárhely": {
				Code: "HV",
			},
			"Jász-Nagykun-Szolnok": {
				Code: "JN",
			},
			"Kaposvár": {
				Code: "KV",
			},
			"Kecskemét": {
				Code: "KM",
			},
			"Komárom-Esztergom": {
				Code: "KE",
			},
			"Miskolc": {
				Code: "MI",
			},
			"Nagykanizsa": {
				Code: "NK",
			},
			"Nyíregyháza": {
				Code: "NY",
			},
			"Nógrád": {
				Code: "NO",
			},
			"Pest": {
				Code: "PE",
			},
			"Pécs": {
				Code: "PS",
			},
			"Salgótarján": {
				Code: "ST",
			},
			"Somogy": {
				Code: "SO",
			},
			"Sopron": {
				Code: "SN",
			},
			"Szabolcs-Szatmár-Bereg": {
				Code: "SZ",
			},
			"Szeged": {
				Code: "SD",
			},
			"Szekszárd": {
				Code: "SS",
			},
			"Szolnok": {
				Code: "SK",
			},
			"Szombathely": {
				Code: "SH",
			},
			"Székesfehérvár": {
				Code: "SF",
			},
			"Tatabánya": {
				Code: "TB",
			},
			"Tolna": {
				Code: "TO",
			},
			"Vas": {
				Code: "VA",
			},
			"Veszprém": {
				Code: "VE",
			},
			"Zala": {
				Code: "ZA",
			},
			"Zalaegerszeg": {
				Code: "ZE",
			},
			"Érd": {
				Code: "ER",
			},
		},
	},

	"ID": {
		Alpha2:       "ID",
		Alpha3:       "IDN",
		Name:         "Indonesia",
		OfficialName: "Republic of Indonesia",
		CommonName:   "",
		Numeric:      "360",
	},

	"IE": {
		Alpha2:       "IE",
		Alpha3:       "IRL",
		Name:         "Ireland",
		OfficialName: "",
		CommonName:   "",
		Numeric:      "372",
	},

	"IL": {
		Alpha2:       "IL",
		Alpha3:       "ISR",
		Name:         "Israel",
		OfficialName: "State of Israel",
		CommonName:   "",
		Numeric:      "376",
	},

	"IM": {
		Alpha2:       "IM",
		Alpha3:       "IMN",
		Name:         "Isle of Man",
		OfficialName: "",
		CommonName:   "",
		Numeric:      "833",
	},

	"IN": {
		Alpha2:       "IN",
		Alpha3:       "IND",
		Name:         "India",
		OfficialName: "Republic of India",
		CommonName:   "",
		Numeric:      "356",
	},

	"IO": {
		Alpha2:       "IO",
		Alpha3:       "IOT",
		Name:         "British Indian Ocean Territory",
		OfficialName: "",
		CommonName:   "",
		Numeric:      "086",
	},

	"IQ": {
		Alpha2:       "IQ",
		Alpha3:       "IRQ",
		Name:         "Iraq",
		OfficialName: "Republic of Iraq",
		CommonName:   "",
		Numeric:      "368",
	},

	"IR": {
		Alpha2:       "IR",
		Alpha3:       "IRN",
		Name:         "Iran, Islamic Republic of",
		OfficialName: "Islamic Republic of Iran",
		CommonName:   "",
		Numeric:      "364",
	},

	"IS": {
		Alpha2:       "IS",
		Alpha3:       "ISL",
		Name:         "Iceland",
		OfficialName: "Republic of Iceland",
		CommonName:   "",
		Numeric:      "352",
	},

	"IT": {
		Alpha2:       "IT",
		Alpha3:       "ITA",
		Name:         "Italy",
		OfficialName: "Italian Republic",
		CommonName:   "",
		Numeric:      "380",
	},

	"JE": {
		Alpha2:       "JE",
		Alpha3:       "JEY",
		Name:         "Jersey",
		OfficialName: "",
		CommonName:   "",
		Numeric:      "832",
	},

	"JM": {
		Alpha2:       "JM",
		Alpha3:       "JAM",
		Name:         "Jamaica",
		OfficialName: "",
		CommonName:   "",
		Numeric:      "388",
	},

	"JO": {
		Alpha2:       "JO",
		Alpha3:       "JOR",
		Name:         "Jordan",
		OfficialName: "Hashemite Kingdom of Jordan",
		CommonName:   "",
		Numeric:      "400",
	},

	"JP": {
		Alpha2:       "JP",
		Alpha3:       "JPN",
		Name:         "Japan",
		OfficialName: "",
		CommonName:   "",
		Numeric:      "392",
	},

	"KE": {
		Alpha2:       "KE",
		Alpha3:       "KEN",
		Name:         "Kenya",
		OfficialName: "Republic of Kenya",
		CommonName:   "",
		Numeric:      "404",
	},

	"KG": {
		Alpha2:       "KG",
		Alpha3:       "KGZ",
		Name:         "Kyrgyzstan",
		OfficialName: "Kyrgyz Republic",
		CommonName:   "",
		Numeric:      "417",
	},

	"KH": {
		Alpha2:       "KH",
		Alpha3:       "KHM",
		Name:         "Cambodia",
		OfficialName: "Kingdom of Cambodia",
		CommonName:   "",
		Numeric:      "116",
	},

	"KI": {
		Alpha2:       "KI",
		Alpha3:       "KIR",
		Name:         "Kiribati",
		OfficialName: "Republic of Kiribati",
		CommonName:   "",
		Numeric:      "296",
	},

	"KM": {
		Alpha2:       "KM",
		Alpha3:       "COM",
		Name:         "Comoros",
		OfficialName: "Union of the Comoros",
		CommonName:   "",
		Numeric:      "174",
	},

	"KN": {
		Alpha2:       "KN",
		Alpha3:       "KNA",
		Name:         "Saint Kitts and Nevis",
		OfficialName: "",
		CommonName:   "",
		Numeric:      "659",
	},

	"KP": {
		Alpha2:       "KP",
		Alpha3:       "PRK",
		Name:         "Korea, Democratic People's Republic of",
		OfficialName: "Democratic People's Republic of Korea",
		CommonName:   "",
		Numeric:      "408",
	},

	"KR": {
		Alpha2:       "KR",
		Alpha3:       "KOR",
		Name:         "Korea, Republic of",
		OfficialName: "",
		CommonName:   "",
		Numeric:      "410",
	},

	"KW": {
		Alpha2:       "KW",
		Alpha3:       "KWT",
		Name:         "Kuwait",
		OfficialName: "State of Kuwait",
		CommonName:   "",
		Numeric:      "414",
	},

	"KY": {
		Alpha2:       "KY",
		Alpha3:       "CYM",
		Name:         "Cayman Islands",
		OfficialName: "",
		CommonName:   "",
		Numeric:      "136",
	},

	"KZ": {
		Alpha2:       "KZ",
		Alpha3:       "KAZ",
		Name:         "Kazakhstan",
		OfficialName: "Republic of Kazakhstan",
		CommonName:   "",
		Numeric:      "398",
	},

	"LA": {
		Alpha2:       "LA",
		Alpha3:       "LAO",
		Name:         "Lao People's Democratic Republic",
		OfficialName: "",
		CommonName:   "",
		Numeric:      "418",
	},

	"LB": {
		Alpha2:       "LB",
		Alpha3:       "LBN",
		Name:         "Lebanon",
		OfficialName: "Lebanese Republic",
		CommonName:   "",
		Numeric:      "422",
	},

	"LC": {
		Alpha2:       "LC",
		Alpha3:       "LCA",
		Name:         "Saint Lucia",
		OfficialName: "",
		CommonName:   "",
		Numeric:      "662",
	},

	"LI": {
		Alpha2:       "LI",
		Alpha3:       "LIE",
		Name:         "Liechtenstein",
		OfficialName: "Principality of Liechtenstein",
		CommonName:   "",
		Numeric:      "438",
	},

	"LK": {
		Alpha2:       "LK",
		Alpha3:       "LKA",
		Name:         "Sri Lanka",
		OfficialName: "Democratic Socialist Republic of Sri Lanka",
		CommonName:   "",
		Numeric:      "144",
	},

	"LR": {
		Alpha2:       "LR",
		Alpha3:       "LBR",
		Name:         "Liberia",
		OfficialName: "Republic of Liberia",
		CommonName:   "",
		Numeric:      "430",
	},

	"LS": {
		Alpha2:       "LS",
		Alpha3:       "LSO",
		Name:         "Lesotho",
		OfficialName: "Kingdom of Lesotho",
		CommonName:   "",
		Numeric:      "426",
	},

	"LT": {
		Alpha2:       "LT",
		Alpha3:       "LTU",
		Name:         "Lithuania",
		OfficialName: "Republic of Lithuania",
		CommonName:   "",
		Numeric:      "440",
	},

	"LU": {
		Alpha2:       "LU",
		Alpha3:       "LUX",
		Name:         "Luxembourg",
		OfficialName: "Grand Duchy of Luxembourg",
		CommonName:   "",
		Numeric:      "442",
	},

	"LV": {
		Alpha2:       "LV",
		Alpha3:       "LVA",
		Name:         "Latvia",
		OfficialName: "Republic of Latvia",
		CommonName:   "",
		Numeric:      "428",
	},

	"LY": {
		Alpha2:       "LY",
		Alpha3:       "LBY",
		Name:         "Libya",
		OfficialName: "Libya",
		CommonName:   "",
		Numeric:      "434",
	},

	"MA": {
		Alpha2:       "MA",
		Alpha3:       "MAR",
		Name:         "Morocco",
		OfficialName: "Kingdom of Morocco",
		CommonName:   "",
		Numeric:      "504",
	},

	"MC": {
		Alpha2:       "MC",
		Alpha3:       "MCO",
		Name:         "Monaco",
		OfficialName: "Principality of Monaco",
		CommonName:   "",
		Numeric:      "492",
	},

	"MD": {
		Alpha2:       "MD",
		Alpha3:       "MDA",
		Name:         "Moldova, Republic of",
		OfficialName: "Republic of Moldova",
		CommonName:   "Moldova",
		Numeric:      "498",
	},

	"ME": {
		Alpha2:       "ME",
		Alpha3:       "MNE",
		Name:         "Montenegro",
		OfficialName: "Montenegro",
		CommonName:   "",
		Numeric:      "499",
	},

	"MF": {
		Alpha2:       "MF",
		Alpha3:       "MAF",
		Name:         "Saint Martin (French part)",
		OfficialName: "",
		CommonName:   "",
		Numeric:      "663",
	},

	"MG": {
		Alpha2:       "MG",
		Alpha3:       "MDG",
		Name:         "Madagascar",
		OfficialName: "Republic of Madagascar",
		CommonName:   "",
		Numeric:      "450",
	},

	"MH": {
		Alpha2:       "MH",
		Alpha3:       "MHL",
		Name:         "Marshall Islands",
		OfficialName: "Republic of the Marshall Islands",
		CommonName:   "",
		Numeric:      "584",
	},

	"MK": {
		Alpha2:       "MK",
		Alpha3:       "MKD",
		Name:         "North Macedonia",
		OfficialName: "Republic of North Macedonia",
		CommonName:   "",
		Numeric:      "807",
	},

	"ML": {
		Alpha2:       "ML",
		Alpha3:       "MLI",
		Name:         "Mali",
		OfficialName: "Republic of Mali",
		CommonName:   "",
		Numeric:      "466",
	},

	"MM": {
		Alpha2:       "MM",
		Alpha3:       "MMR",
		Name:         "Myanmar",
		OfficialName: "Republic of Myanmar",
		CommonName:   "",
		Numeric:      "104",
	},

	"MN": {
		Alpha2:       "MN",
		Alpha3:       "MNG",
		Name:         "Mongolia",
		OfficialName: "",
		CommonName:   "",
		Numeric:      "496",
	},

	"MO": {
		Alpha2:       "MO",
		Alpha3:       "MAC",
		Name:         "Macao",
		OfficialName: "Macao Special Administrative Region of China",
		CommonName:   "",
		Numeric:      "446",
	},

	"MP": {
		Alpha2:       "MP",
		Alpha3:       "MNP",
		Name:         "Northern Mariana Islands",
		OfficialName: "Commonwealth of the Northern Mariana Islands",
		CommonName:   "",
		Numeric:      "580",
	},

	"MQ": {
		Alpha2:       "MQ",
		Alpha3:       "MTQ",
		Name:         "Martinique",
		OfficialName: "",
		CommonName:   "",
		Numeric:      "474",
	},

	"MR": {
		Alpha2:       "MR",
		Alpha3:       "MRT",
		Name:         "Mauritania",
		OfficialName: "Islamic Republic of Mauritania",
		CommonName:   "",
		Numeric:      "478",
	},

	"MS": {
		Alpha2:       "MS",
		Alpha3:       "MSR",
		Name:         "Montserrat",
		OfficialName: "",
		CommonName:   "",
		Numeric:      "500",
	},

	"MT": {
		Alpha2:       "MT",
		Alpha3:       "MLT",
		Name:         "Malta",
		OfficialName: "Republic of Malta",
		CommonName:   "",
		Numeric:      "470",
	},

	"MU": {
		Alpha2:       "MU",
		Alpha3:       "MUS",
		Name:         "Mauritius",
		OfficialName: "Republic of Mauritius",
		CommonName:   "",
		Numeric:      "480",
	},

	"MV": {
		Alpha2:       "MV",
		Alpha3:       "MDV",
		Name:         "Maldives",
		OfficialName: "Republic of Maldives",
		CommonName:   "",
		Numeric:      "462",
	},

	"MW": {
		Alpha2:       "MW",
		Alpha3:       "MWI",
		Name:         "Malawi",
		OfficialName: "Republic of Malawi",
		CommonName:   "",
		Numeric:      "454",
	},

	"MX": {
		Alpha2:       "MX",
		Alpha3:       "MEX",
		Name:         "Mexico",
		OfficialName: "United Mexican States",
		CommonName:   "",
		Numeric:      "484",
	},

	"MY": {
		Alpha2:       "MY",
		Alpha3:       "MYS",
		Name:         "Malaysia",
		OfficialName: "",
		CommonName:   "",
		Numeric:      "458",
	},

	"MZ": {
		Alpha2:       "MZ",
		Alpha3:       "MOZ",
		Name:         "Mozambique",
		OfficialName: "Republic of Mozambique",
		CommonName:   "",
		Numeric:      "508",
	},

	"NA": {
		Alpha2:       "NA",
		Alpha3:       "NAM",
		Name:         "Namibia",
		OfficialName: "Republic of Namibia",
		CommonName:   "",
		Numeric:      "516",
	},

	"NC": {
		Alpha2:       "NC",
		Alpha3:       "NCL",
		Name:         "New Caledonia",
		OfficialName: "",
		CommonName:   "",
		Numeric:      "540",
	},

	"NE": {
		Alpha2:       "NE",
		Alpha3:       "NER",
		Name:         "Niger",
		OfficialName: "Republic of the Niger",
		CommonName:   "",
		Numeric:      "562",
	},

	"NF": {
		Alpha2:       "NF",
		Alpha3:       "NFK",
		Name:         "Norfolk Island",
		OfficialName: "",
		CommonName:   "",
		Numeric:      "574",
	},

	"NG": {
		Alpha2:       "NG",
		Alpha3:       "NGA",
		Name:         "Nigeria",
		OfficialName: "Federal Republic of Nigeria",
		CommonName:   "",
		Numeric:      "566",
	},

	"NI": {
		Alpha2:       "NI",
		Alpha3:       "NIC",
		Name:         "Nicaragua",
		OfficialName: "Republic of Nicaragua",
		CommonName:   "",
		Numeric:      "558",
	},

	"NL": {
		Alpha2:       "NL",
		Alpha3:       "NLD",
		Name:         "Netherlands",
		OfficialName: "Kingdom of the Netherlands",
		CommonName:   "",
		Numeric:      "528",
	},

	"NO": {
		Alpha2:       "NO",
		Alpha3:       "NOR",
		Name:         "Norway",
		OfficialName: "Kingdom of Norway",
		CommonName:   "",
		Numeric:      "578",
	},

	"NP": {
		Alpha2:       "NP",
		Alpha3:       "NPL",
		Name:         "Nepal",
		OfficialName: "Federal Democratic Republic of Nepal",
		CommonName:   "",
		Numeric:      "524",
	},

	"NR": {
		Alpha2:       "NR",
		Alpha3:       "NRU",
		Name:         "Nauru",
		OfficialName: "Republic of Nauru",
		CommonName:   "",
		Numeric:      "520",
	},

	"NU": {
		Alpha2:       "NU",
		Alpha3:       "NIU",
		Name:         "Niue",
		OfficialName: "Niue",
		CommonName:   "",
		Numeric:      "570",
	},

	"NZ": {
		Alpha2:       "NZ",
		Alpha3:       "NZL",
		Name:         "New Zealand",
		OfficialName: "",
		CommonName:   "",
		Numeric:      "554",
	},

	"OM": {
		Alpha2:       "OM",
		Alpha3:       "OMN",
		Name:         "Oman",
		OfficialName: "Sultanate of Oman",
		CommonName:   "",
		Numeric:      "512",
	},

	"PA": {
		Alpha2:       "PA",
		Alpha3:       "PAN",
		Name:         "Panama",
		OfficialName: "Republic of Panama",
		CommonName:   "",
		Numeric:      "591",
	},

	"PE": {
		Alpha2:       "PE",
		Alpha3:       "PER",
		Name:         "Peru",
		OfficialName: "Republic of Peru",
		CommonName:   "",
		Numeric:      "604",
	},

	"PF": {
		Alpha2:       "PF",
		Alpha3:       "PYF",
		Name:         "French Polynesia",
		OfficialName: "",
		CommonName:   "",
		Numeric:      "258",
	},

	"PG": {
		Alpha2:       "PG",
		Alpha3:       "PNG",
		Name:         "Papua New Guinea",
		OfficialName: "Independent State of Papua New Guinea",
		CommonName:   "",
		Numeric:      "598",
	},

	"PH": {
		Alpha2:       "PH",
		Alpha3:       "PHL",
		Name:         "Philippines",
		OfficialName: "Republic of the Philippines",
		CommonName:   "",
		Numeric:      "608",
	},

	"PK": {
		Alpha2:       "PK",
		Alpha3:       "PAK",
		Name:         "Pakistan",
		OfficialName: "Islamic Republic of Pakistan",
		CommonName:   "",
		Numeric:      "586",
	},

	"PL": {
		Alpha2:       "PL",
		Alpha3:       "POL",
		Name:         "Poland",
		OfficialName: "Republic of Poland",
		CommonName:   "",
		Numeric:      "616",
	},

	"PM": {
		Alpha2:       "PM",
		Alpha3:       "SPM",
		Name:         "Saint Pierre and Miquelon",
		OfficialName: "",
		CommonName:   "",
		Numeric:      "666",
	},

	"PN": {
		Alpha2:       "PN",
		Alpha3:       "PCN",
		Name:         "Pitcairn",
		OfficialName: "",
		CommonName:   "",
		Numeric:      "612",
	},

	"PR": {
		Alpha2:       "PR",
		Alpha3:       "PRI",
		Name:         "Puerto Rico",
		OfficialName: "",
		CommonName:   "",
		Numeric:      "630",
	},

	"PS": {
		Alpha2:       "PS",
		Alpha3:       "PSE",
		Name:         "Palestine, State of",
		OfficialName: "the State of Palestine",
		CommonName:   "",
		Numeric:      "275",
	},

	"PT": {
		Alpha2:       "PT",
		Alpha3:       "PRT",
		Name:         "Portugal",
		OfficialName: "Portuguese Republic",
		CommonName:   "",
		Numeric:      "620",
	},

	"PW": {
		Alpha2:       "PW",
		Alpha3:       "PLW",
		Name:         "Palau",
		OfficialName: "Republic of Palau",
		CommonName:   "",
		Numeric:      "585",
	},

	"PY": {
		Alpha2:       "PY",
		Alpha3:       "PRY",
		Name:         "Paraguay",
		OfficialName: "Republic of Paraguay",
		CommonName:   "",
		Numeric:      "600",
	},

	"QA": {
		Alpha2:       "QA",
		Alpha3:       "QAT",
		Name:         "Qatar",
		OfficialName: "State of Qatar",
		CommonName:   "",
		Numeric:      "634",
	},

	"RE": {
		Alpha2:       "RE",
		Alpha3:       "REU",
		Name:         "Réunion",
		OfficialName: "",
		CommonName:   "",
		Numeric:      "638",
	},

	"RO": {
		Alpha2:       "RO",
		Alpha3:       "ROU",
		Name:         "Romania",
		OfficialName: "",
		CommonName:   "",
		Numeric:      "642",
	},

	"RS": {
		Alpha2:       "RS",
		Alpha3:       "SRB",
		Name:         "Serbia",
		OfficialName: "Republic of Serbia",
		CommonName:   "",
		Numeric:      "688",

		SubDivCodeToName: map[string]SubDivisionNameWrapper{

			"00": {
				Name:         "Beograd",
				LocalName:    "",
				LanguageCode: "sr",
				Type:         "city",
			},
			"08": {
				Name:         "Mačvanski okrug",
				LocalName:    "",
				LanguageCode: "sr",
				Type:         "district",
			},
			"09": {
				Name:         "Kolubarski okrug",
				LocalName:    "",
				LanguageCode: "sr",
				Type:         "district",
			},
			"10": {
				Name:         "Podunavski okrug",
				LocalName:    "",
				LanguageCode: "sr",
				Type:         "district",
			},
			"11": {
				Name:         "Braničevski okrug",
				LocalName:    "",
				LanguageCode: "sr",
				Type:         "district",
			},
			"12": {
				Name:         "Šumadijski okrug",
				LocalName:    "",
				LanguageCode: "sr",
				Type:         "district",
			},
			"13": {
				Name:         "Pomoravski okrug",
				LocalName:    "",
				LanguageCode: "sr",
				Type:         "district",
			},
			"14": {
				Name:         "Borski okrug",
				LocalName:    "",
				LanguageCode: "sr",
				Type:         "district",
			},
			"15": {
				Name:         "Zaječarski okrug",
				LocalName:    "",
				LanguageCode: "sr",
				Type:         "district",
			},
			"16": {
				Name:         "Zlatiborski okrug",
				LocalName:    "",
				LanguageCode: "sr",
				Type:         "district",
			},
			"17": {
				Name:         "Moravički okrug",
				LocalName:    "",
				LanguageCode: "sr",
				Type:         "district",
			},
			"18": {
				Name:         "Raški okrug",
				LocalName:    "",
				LanguageCode: "sr",
				Type:         "district",
			},
			"19": {
				Name:         "Rasinski okrug",
				LocalName:    "",
				LanguageCode: "sr",
				Type:         "district",
			},
			"20": {
				Name:         "Nišavski okrug",
				LocalName:    "",
				LanguageCode: "sr",
				Type:         "district",
			},
			"21": {
				Name:         "Toplički okrug",
				LocalName:    "",
				LanguageCode: "sr",
				Type:         "district",
			},
			"22": {
				Name:         "Pirotski okrug",
				LocalName:    "",
				LanguageCode: "sr",
				Type:         "district",
			},
			"23": {
				Name:         "Jablanički okrug",
				LocalName:    "",
				LanguageCode: "sr",
				Type:         "district",
			},
			"24": {
				Name:         "Pčinjski okrug",
				LocalName:    "",
				LanguageCode: "sr",
				Type:         "district",
			},
			"KM": {
				Name:         "Kosovo-Metohija",
				LocalName:    "",
				LanguageCode: "sr",
				Type:         "autonomous province",

				SubDivCodeToName: map[string]SubDivisionNameWrapper{

					"25": {
						Name:         "Kosovski okrug",
						LocalName:    "",
						LanguageCode: "sr",
						Type:         "district",
					},
					"26": {
						Name:         "Pećki okrug",
						LocalName:    "",
						LanguageCode: "sr",
						Type:         "district",
					},
					"27": {
						Name:         "Prizrenski okrug",
						LocalName:    "",
						LanguageCode: "sr",
						Type:         "district",
					},
					"28": {
						Name:         "Kosovsko-Mitrovački okrug",
						LocalName:    "",
						LanguageCode: "sr",
						Type:         "district",
					},
					"29": {
						Name:         "Kosovsko-Pomoravski okrug",
						LocalName:    "",
						LanguageCode: "sr",
						Type:         "district",
					},
				},
			},
			"VO": {
				Name:         "Vojvodina",
				LocalName:    "",
				LanguageCode: "sr",
				Type:         "autonomous province",

				SubDivCodeToName: map[string]SubDivisionNameWrapper{

					"01": {
						Name:         "Severnobački okrug",
						LocalName:    "",
						LanguageCode: "sr",
						Type:         "district",
					},
					"02": {
						Name:         "Srednjebanatski okrug",
						LocalName:    "",
						LanguageCode: "sr",
						Type:         "district",
					},
					"03": {
						Name:         "Severnobanatski okrug",
						LocalName:    "",
						LanguageCode: "sr",
						Type:         "district",
					},
					"04": {
						Name:         "Južnobanatski okrug",
						LocalName:    "",
						LanguageCode: "sr",
						Type:         "district",
					},
					"05": {
						Name:         "Zapadnobački okrug",
						LocalName:    "",
						LanguageCode: "sr",
						Type:         "district",
					},
					"06": {
						Name:         "Južnobački okrug",
						LocalName:    "",
						LanguageCode: "sr",
						Type:         "district",
					},
					"07": {
						Name:         "Sremski okrug",
						LocalName:    "",
						LanguageCode: "sr",
						Type:         "district",
					},
				},
			},
		},

		SubDivNameToCode: map[string]SubDivisionCodeWrapper{

			"Beograd": {
				Code: "00",
			},
			"Borski okrug": {
				Code: "14",
			},
			"Braničevski okrug": {
				Code: "11",
			},
			"Jablanički okrug": {
				Code: "23",
			},
			"Kolubarski okrug": {
				Code: "09",
			},
			"Kosovo-Metohija": {
				Code: "KM",

				SubDivNameToCode: map[string]SubDivisionCodeWrapper{

					"Kosovski okrug": {
						Code: "25",
					},
					"Kosovsko-Mitrovački okrug": {
						Code: "28",
					},
					"Kosovsko-Pomoravski okrug": {
						Code: "29",
					},
					"Pećki okrug": {
						Code: "26",
					},
					"Prizrenski okrug": {
						Code: "27",
					},
				},
			},
			"Mačvanski okrug": {
				Code: "08",
			},
			"Moravički okrug": {
				Code: "17",
			},
			"Nišavski okrug": {
				Code: "20",
			},
			"Pirotski okrug": {
				Code: "22",
			},
			"Podunavski okrug": {
				Code: "10",
			},
			"Pomoravski okrug": {
				Code: "13",
			},
			"Pčinjski okrug": {
				Code: "24",
			},
			"Rasinski okrug": {
				Code: "19",
			},
			"Raški okrug": {
				Code: "18",
			},
			"Toplički okrug": {
				Code: "21",
			},
			"Vojvodina": {
				Code: "VO",

				SubDivNameToCode: map[string]SubDivisionCodeWrapper{

					"Južnobanatski okrug": {
						Code: "04",
					},
					"Južnobački okrug": {
						Code: "06",
					},
					"Severnobanatski okrug": {
						Code: "03",
					},
					"Severnobački okrug": {
						Code: "01",
					},
					"Srednjebanatski okrug": {
						Code: "02",
					},
					"Sremski okrug": {
						Code: "07",
					},
					"Zapadnobački okrug": {
						Code: "05",
					},
				},
			},
			"Zaječarski okrug": {
				Code: "15",
			},
			"Zlatiborski okrug": {
				Code: "16",
			},
			"Šumadijski okrug": {
				Code: "12",
			},
		},
	},

	"RU": {
		Alpha2:       "RU",
		Alpha3:       "RUS",
		Name:         "Russian Federation",
		OfficialName: "",
		CommonName:   "",
		Numeric:      "643",
	},

	"RW": {
		Alpha2:       "RW",
		Alpha3:       "RWA",
		Name:         "Rwanda",
		OfficialName: "Rwandese Republic",
		CommonName:   "",
		Numeric:      "646",
	},

	"SA": {
		Alpha2:       "SA",
		Alpha3:       "SAU",
		Name:         "Saudi Arabia",
		OfficialName: "Kingdom of Saudi Arabia",
		CommonName:   "",
		Numeric:      "682",
	},

	"SB": {
		Alpha2:       "SB",
		Alpha3:       "SLB",
		Name:         "Solomon Islands",
		OfficialName: "",
		CommonName:   "",
		Numeric:      "090",
	},

	"SC": {
		Alpha2:       "SC",
		Alpha3:       "SYC",
		Name:         "Seychelles",
		OfficialName: "Republic of Seychelles",
		CommonName:   "",
		Numeric:      "690",
	},

	"SD": {
		Alpha2:       "SD",
		Alpha3:       "SDN",
		Name:         "Sudan",
		OfficialName: "Republic of the Sudan",
		CommonName:   "",
		Numeric:      "729",
	},

	"SE": {
		Alpha2:       "SE",
		Alpha3:       "SWE",
		Name:         "Sweden",
		OfficialName: "Kingdom of Sweden",
		CommonName:   "",
		Numeric:      "752",
	},

	"SG": {
		Alpha2:       "SG",
		Alpha3:       "SGP",
		Name:         "Singapore",
		OfficialName: "Republic of Singapore",
		CommonName:   "",
		Numeric:      "702",
	},

	"SH": {
		Alpha2:       "SH",
		Alpha3:       "SHN",
		Name:         "Saint Helena, Ascension and Tristan da Cunha",
		OfficialName: "",
		CommonName:   "",
		Numeric:      "654",
	},

	"SI": {
		Alpha2:       "SI",
		Alpha3:       "SVN",
		Name:         "Slovenia",
		OfficialName: "Republic of Slovenia",
		CommonName:   "",
		Numeric:      "705",
	},

	"SJ": {
		Alpha2:       "SJ",
		Alpha3:       "SJM",
		Name:         "Svalbard and Jan Mayen",
		OfficialName: "",
		CommonName:   "",
		Numeric:      "744",
	},

	"SK": {
		Alpha2:       "SK",
		Alpha3:       "SVK",
		Name:         "Slovakia",
		OfficialName: "Slovak Republic",
		CommonName:   "",
		Numeric:      "703",
	},

	"SL": {
		Alpha2:       "SL",
		Alpha3:       "SLE",
		Name:         "Sierra Leone",
		OfficialName: "Republic of Sierra Leone",
		CommonName:   "",
		Numeric:      "694",
	},

	"SM": {
		Alpha2:       "SM",
		Alpha3:       "SMR",
		Name:         "San Marino",
		OfficialName: "Republic of San Marino",
		CommonName:   "",
		Numeric:      "674",
	},

	"SN": {
		Alpha2:       "SN",
		Alpha3:       "SEN",
		Name:         "Senegal",
		OfficialName: "Republic of Senegal",
		CommonName:   "",
		Numeric:      "686",
	},

	"SO": {
		Alpha2:       "SO",
		Alpha3:       "SOM",
		Name:         "Somalia",
		OfficialName: "Federal Republic of Somalia",
		CommonName:   "",
		Numeric:      "706",
	},

	"SR": {
		Alpha2:       "SR",
		Alpha3:       "SUR",
		Name:         "Suriname",
		OfficialName: "Republic of Suriname",
		CommonName:   "",
		Numeric:      "740",
	},

	"SS": {
		Alpha2:       "SS",
		Alpha3:       "SSD",
		Name:         "South Sudan",
		OfficialName: "Republic of South Sudan",
		CommonName:   "",
		Numeric:      "728",
	},

	"ST": {
		Alpha2:       "ST",
		Alpha3:       "STP",
		Name:         "Sao Tome and Principe",
		OfficialName: "Democratic Republic of Sao Tome and Principe",
		CommonName:   "",
		Numeric:      "678",
	},

	"SV": {
		Alpha2:       "SV",
		Alpha3:       "SLV",
		Name:         "El Salvador",
		OfficialName: "Republic of El Salvador",
		CommonName:   "",
		Numeric:      "222",
	},

	"SX": {
		Alpha2:       "SX",
		Alpha3:       "SXM",
		Name:         "Sint Maarten (Dutch part)",
		OfficialName: "Sint Maarten (Dutch part)",
		CommonName:   "",
		Numeric:      "534",
	},

	"SY": {
		Alpha2:       "SY",
		Alpha3:       "SYR",
		Name:         "Syrian Arab Republic",
		OfficialName: "",
		CommonName:   "",
		Numeric:      "760",
	},

	"SZ": {
		Alpha2:       "SZ",
		Alpha3:       "SWZ",
		Name:         "Eswatini",
		OfficialName: "Kingdom of Eswatini",
		CommonName:   "",
		Numeric:      "748",
	},

	"TC": {
		Alpha2:       "TC",
		Alpha3:       "TCA",
		Name:         "Turks and Caicos Islands",
		OfficialName: "",
		CommonName:   "",
		Numeric:      "796",
	},

	"TD": {
		Alpha2:       "TD",
		Alpha3:       "TCD",
		Name:         "Chad",
		OfficialName: "Republic of Chad",
		CommonName:   "",
		Numeric:      "148",
	},

	"TF": {
		Alpha2:       "TF",
		Alpha3:       "ATF",
		Name:         "French Southern Territories",
		OfficialName: "",
		CommonName:   "",
		Numeric:      "260",
	},

	"TG": {
		Alpha2:       "TG",
		Alpha3:       "TGO",
		Name:         "Togo",
		OfficialName: "Togolese Republic",
		CommonName:   "",
		Numeric:      "768",
	},

	"TH": {
		Alpha2:       "TH",
		Alpha3:       "THA",
		Name:         "Thailand",
		OfficialName: "Kingdom of Thailand",
		CommonName:   "",
		Numeric:      "764",
	},

	"TJ": {
		Alpha2:       "TJ",
		Alpha3:       "TJK",
		Name:         "Tajikistan",
		OfficialName: "Republic of Tajikistan",
		CommonName:   "",
		Numeric:      "762",
	},

	"TK": {
		Alpha2:       "TK",
		Alpha3:       "TKL",
		Name:         "Tokelau",
		OfficialName: "",
		CommonName:   "",
		Numeric:      "772",
	},

	"TL": {
		Alpha2:       "TL",
		Alpha3:       "TLS",
		Name:         "Timor-Leste",
		OfficialName: "Democratic Republic of Timor-Leste",
		CommonName:   "",
		Numeric:      "626",
	},

	"TM": {
		Alpha2:       "TM",
		Alpha3:       "TKM",
		Name:         "Turkmenistan",
		OfficialName: "",
		CommonName:   "",
		Numeric:      "795",
	},

	"TN": {
		Alpha2:       "TN",
		Alpha3:       "TUN",
		Name:         "Tunisia",
		OfficialName: "Republic of Tunisia",
		CommonName:   "",
		Numeric:      "788",
	},

	"TO": {
		Alpha2:       "TO",
		Alpha3:       "TON",
		Name:         "Tonga",
		OfficialName: "Kingdom of Tonga",
		CommonName:   "",
		Numeric:      "776",
	},

	"TR": {
		Alpha2:       "TR",
		Alpha3:       "TUR",
		Name:         "Turkey",
		OfficialName: "Republic of Turkey",
		CommonName:   "",
		Numeric:      "792",
	},

	"TT": {
		Alpha2:       "TT",
		Alpha3:       "TTO",
		Name:         "Trinidad and Tobago",
		OfficialName: "Republic of Trinidad and Tobago",
		CommonName:   "",
		Numeric:      "780",
	},

	"TV": {
		Alpha2:       "TV",
		Alpha3:       "TUV",
		Name:         "Tuvalu",
		OfficialName: "",
		CommonName:   "",
		Numeric:      "798",
	},

	"TW": {
		Alpha2:       "TW",
		Alpha3:       "TWN",
		Name:         "Taiwan, Province of China",
		OfficialName: "Taiwan, Province of China",
		CommonName:   "Taiwan",
		Numeric:      "158",
	},

	"TZ": {
		Alpha2:       "TZ",
		Alpha3:       "TZA",
		Name:         "Tanzania, United Republic of",
		OfficialName: "United Republic of Tanzania",
		CommonName:   "Tanzania",
		Numeric:      "834",
	},

	"UA": {
		Alpha2:       "UA",
		Alpha3:       "UKR",
		Name:         "Ukraine",
		OfficialName: "",
		CommonName:   "",
		Numeric:      "804",
	},

	"UG": {
		Alpha2:       "UG",
		Alpha3:       "UGA",
		Name:         "Uganda",
		OfficialName: "Republic of Uganda",
		CommonName:   "",
		Numeric:      "800",
	},

	"UM": {
		Alpha2:       "UM",
		Alpha3:       "UMI",
		Name:         "United States Minor Outlying Islands",
		OfficialName: "",
		CommonName:   "",
		Numeric:      "581",
	},

	"US": {
		Alpha2:       "US",
		Alpha3:       "USA",
		Name:         "United States",
		OfficialName: "United States of America",
		CommonName:   "",
		Numeric:      "840",
	},

	"UY": {
		Alpha2:       "UY",
		Alpha3:       "URY",
		Name:         "Uruguay",
		OfficialName: "Eastern Republic of Uruguay",
		CommonName:   "",
		Numeric:      "858",
	},

	"UZ": {
		Alpha2:       "UZ",
		Alpha3:       "UZB",
		Name:         "Uzbekistan",
		OfficialName: "Republic of Uzbekistan",
		CommonName:   "",
		Numeric:      "860",
	},

	"VA": {
		Alpha2:       "VA",
		Alpha3:       "VAT",
		Name:         "Holy See (Vatican City State)",
		OfficialName: "",
		CommonName:   "",
		Numeric:      "336",
	},

	"VC": {
		Alpha2:       "VC",
		Alpha3:       "VCT",
		Name:         "Saint Vincent and the Grenadines",
		OfficialName: "",
		CommonName:   "",
		Numeric:      "670",
	},

	"VE": {
		Alpha2:       "VE",
		Alpha3:       "VEN",
		Name:         "Venezuela, Bolivarian Republic of",
		OfficialName: "Bolivarian Republic of Venezuela",
		CommonName:   "Venezuela",
		Numeric:      "862",
	},

	"VG": {
		Alpha2:       "VG",
		Alpha3:       "VGB",
		Name:         "Virgin Islands, British",
		OfficialName: "British Virgin Islands",
		CommonName:   "",
		Numeric:      "092",
	},

	"VI": {
		Alpha2:       "VI",
		Alpha3:       "VIR",
		Name:         "Virgin Islands, U.S.",
		OfficialName: "Virgin Islands of the United States",
		CommonName:   "",
		Numeric:      "850",
	},

	"VN": {
		Alpha2:       "VN",
		Alpha3:       "VNM",
		Name:         "Viet Nam",
		OfficialName: "Socialist Republic of Viet Nam",
		CommonName:   "Vietnam",
		Numeric:      "704",
	},

	"VU": {
		Alpha2:       "VU",
		Alpha3:       "VUT",
		Name:         "Vanuatu",
		OfficialName: "Republic of Vanuatu",
		CommonName:   "",
		Numeric:      "548",
	},

	"WF": {
		Alpha2:       "WF",
		Alpha3:       "WLF",
		Name:         "Wallis and Futuna",
		OfficialName: "",
		CommonName:   "",
		Numeric:      "876",
	},

	"WS": {
		Alpha2:       "WS",
		Alpha3:       "WSM",
		Name:         "Samoa",
		OfficialName: "Independent State of Samoa",
		CommonName:   "",
		Numeric:      "882",
	},

	"YE": {
		Alpha2:       "YE",
		Alpha3:       "YEM",
		Name:         "Yemen",
		OfficialName: "Republic of Yemen",
		CommonName:   "",
		Numeric:      "887",
	},

	"YT": {
		Alpha2:       "YT",
		Alpha3:       "MYT",
		Name:         "Mayotte",
		OfficialName: "",
		CommonName:   "",
		Numeric:      "175",
	},

	"ZA": {
		Alpha2:       "ZA",
		Alpha3:       "ZAF",
		Name:         "South Africa",
		OfficialName: "Republic of South Africa",
		CommonName:   "",
		Numeric:      "710",
	},

	"ZM": {
		Alpha2:       "ZM",
		Alpha3:       "ZMB",
		Name:         "Zambia",
		OfficialName: "Republic of Zambia",
		CommonName:   "",
		Numeric:      "894",
	},

	"ZW": {
		Alpha2:       "ZW",
		Alpha3:       "ZWE",
		Name:         "Zimbabwe",
		OfficialName: "Republic of Zimbabwe",
		CommonName:   "",
		Numeric:      "716",
	},
}
